services:
  - type: web
    name: sign-language-app
    env: node
    rootDir: .
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
