services:
  - type: web
    name: sign-language-app
    env: node
    buildCommand: npm install && npm run build && node seed.js
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
